# Generated by Django 4.1.7 on 2023-03-30 16:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faculty',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
