# Generated by Django 4.1.7 on 2023-03-28 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='faculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='management.faculty'),
        ),
        migrations.AlterField(
            model_name='student',
            name='regular_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.class'),
        ),
    ]
