# Generated by Django 4.1.7 on 2023-05-02 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_alter_mark_course_alter_mark_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='is_locked',
            new_name='locked',
        ),
    ]
