# Generated by Django 4.1.7 on 2023-05-03 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_rename_is_locked_course_locked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='locked',
        ),
    ]
