# Generated by Django 4.1.7 on 2023-04-25 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_alter_student_user_alter_teacher_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentUser',
        ),
        migrations.DeleteModel(
            name='TeacherUser',
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('subject', 'course_class')},
        ),
    ]
