# Generated by Django 4.1.7 on 2023-04-26 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_delete_studentuser_delete_teacheruser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('DONE', 'Done')], default='DRAFT', max_length=50),
        ),
        migrations.AlterField(
            model_name='mark',
            name='course',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='management.course'),
        ),
    ]
