# Generated by Django 4.1.7 on 2023-04-28 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_mark_status_alter_mark_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mark',
            name='status',
        ),
        migrations.AddField(
            model_name='course',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='result_status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('DONE', 'Done')], default='DRAFT', max_length=50),
        ),
        migrations.AlterField(
            model_name='mark',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='management.student'),
        ),
    ]
